# Generated by Django 6.0.3 on 2026-03-19 17:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                (
                    "isbn_13",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("genre", models.CharField(blank=True, default="", max_length=100)),
                ("published_year", models.IntegerField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, default="", max_length=300)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("cover_url", models.URLField(blank=True, default="")),
                (
                    "normalized_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "normalized_author",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("genre_confidence", models.FloatField(default=0.0)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("upvote_count", models.IntegerField(default=0)),
                ("downvote_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("cleaned_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["quality_score"], name="books_book_quality_59114e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_flagged"], name="books_book_is_flag_dfda28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["average_rating"], name="books_book_average_ee2613_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookrating",
            unique_together={("book", "user")},
        ),
    ]
